### ISSUE TITLE
[Feature]: Performance & Resiliency update for MIOpen applicability checking

### ISSUE THREAD

**Issue by cderb** [ROCmSoftwarePlatform/MITunaX#961]
The applicability check in fin_class is currently designed to distribute work to processes relative to the available number of compute threads on one machine.
There are some performance issues with submitting the result queries to sql and rejoining all of the processes created upon completion.
Since applicability is cleared at the start and results are committed upon completion, there is a significant window in which results could be lost due to early termination or sql interaction failures.
This code would benefit from some more resiliency and abbreviated result commit times.

**Comment by msaudulhassan** [comment]
@cderb @alexandraBara I was wondering if this will get addressed through Alex's Celery update?

**Comment by cderb** [comment]
resolving in pr
https://github.com/ROCm/MITuna/pull/967
